### ISSUE TITLE
ng2-monaco-editor.ts is missing from the TypeScript compilation

### ISSUE THREAD

**Issue by chintancmarix** [0plus1/ng2-monaco-editor#8]
I upgrade to Angular 5.1, after that, I am getting following Error in my project at the time of `ng serve`.

ERROR in ./node_modules/ng2-monaco-editor/ng2-monaco-editor.ts
Module build failed: Error: `~.\node_modules\ng2-monaco-editor\ng2-monaco-editor.ts` is missing from the TypeScript compilation. Please make sure it is in your tsconfig via the 'files' or 'include' property.
The missing file seems to be part of a third party library. TS files in published libraries are often a sign of a badly packaged library. Please open an issue in the library repository to alert its author and ask them to package the library using the Angular Package Format (https://goo.gl/jB3GVv).
    at AngularCompilerPlugin.getCompiledFile (`~.\node_modules\@ngtools\webpack\src\angular_compiler_plugin.js:653:23`)
    at plugin.done.then (`~.\node_modules\@ngtools\webpack\src\loader.js:467:39`)
    at process._tickCallback (`internal/process/next_tick.js:103:7`)
 @ ./src/app/app.module.ts 22:26-54
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

It was working on the Angular 4.xx version. I tried multiple ways to resolve the issue. But, I am still failing to resolve this issue. Please guide me to resolve this issue.

**Comment by fweinrich** [comment]
Hey,
I forked the project and updated it. I'll clean it up later and create a pull request.
For now you can just use https://www.npmjs.com/package/ng5-monaco instead of this repo.

**Comment by joecot** [comment]
I ended up switching to ngx-monaco-editor:
https://github.com/atularen/ngx-monaco-editor
Which appears to be far better maintained than this project. ng2-monaco-editor was last updated November 2016. ngx-monaco-editor was updated 4 days ago.
